# Generated by Django 3.0.6 on 2020-06-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20200609_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='MEDIA_COMPANY_IMAGE_DIR'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='picture',
            field=models.ImageField(blank=True, upload_to='MEDIA_SPECIALITY_IMAGE_DIR'),
        ),
    ]
