# Generated by Django 3.0.6 on 2020-06-12 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vacancy.data


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancy', '0006_auto_20200612_1625'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[(vacancy.data.WorkStatusChoices['not_in_search'], 'Не ищу работу'), (vacancy.data.WorkStatusChoices['consideration'], 'Рассматриваю предложения'), (vacancy.data.WorkStatusChoices['in_search'], 'Ищу работу')], max_length=255)),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('grade', models.CharField(choices=[(vacancy.data.GradeChoices['intern'], 'intern'), (vacancy.data.GradeChoices['junior'], 'junior'), (vacancy.data.GradeChoices['middle'], 'middle'), (vacancy.data.GradeChoices['senior'], 'senior'), (vacancy.data.GradeChoices['lead'], 'lead')], max_length=255)),
                ('education', models.CharField(choices=[(vacancy.data.EducationChoices['missing'], 'Отсутствует'), (vacancy.data.EducationChoices['secondary'], 'Среднее'), (vacancy.data.EducationChoices['vocational'], 'Средне-специальное'), (vacancy.data.EducationChoices['incomplete_higher'], 'Неполное высшее'), (vacancy.data.EducationChoices['higher'], 'Высшее')], max_length=255)),
                ('experience', models.CharField(max_length=100)),
                ('portfolio', models.URLField(blank=True, verbose_name='portfolio')),
                ('speciality', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='resume', to='vacancy.Speciality', verbose_name='специализация')),
                ('user', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
